### ISSUE TITLE
only CPU information

### ISSUE THREAD

**Issue by diepnt90** [RehabMan/OS-X-FakeSMC-kozlek#11]
Hi,

I installed FakeSMC and 4 plugin kexts into Clover/Kexts but only CPU information shows.

how to show other information like fan speed, hard disk...

**Comment by diepnt90** [comment]
![screen shot 2017-03-18 at 21 53 15](https://cloud.githubusercontent.com/assets/18731180/24073158/9866e9a2-0c25-11e7-95cc-06090ce54800.png)

**Comment by RehabMan** [comment]
Support for other sensors is either:
- dependent on hardware (whether support exists for your hardware in FakeSMC_LPCSensors.kext, FakeSMC_GPUSensors.kext)
- or dependent on you implementing the required ACPI code for additional sensors to interface to FakeSMC_ACPISensors.kext
