### ISSUE TITLE
Fan Speed Increased after Updating FakeSMC

### ISSUE THREAD

**Issue by Niresh12495** [RehabMan/OS-X-FakeSMC-kozlek#12]
I was using fakeSMC plugins from RehabMan-FakeSMC-2017-0117.zip release after updating to RehabMan-FakeSMC-2017-0414.zip release my fan speed started to increase and very noisy

Where are the debug kexts located?
Should i include something here, please include steps thanks
Maximus ranger VIII

**Comment by RehabMan** [comment]
You should try to determine which plugin is causing the problem.
Debug kexts must be built from source.

**Comment by Niresh12495** [comment]
Actually it is not FakeSMC Plugins, it is FakeSMC itself causing the issue

**Comment by RehabMan** [comment]
See if it happens with kozlek's build.  If it does, report to kozlek...
He made a lot of changes here (many probably not needed, change for change sake...)
I may back them out, and implement only the KabyLake changes in my own fork...

**Comment by Niresh12495** [comment]
This is the commit
https://github.com/kozlek/HWSensors/commit/0d00fecf6cce2c6198402c93397439a9fe8a4d07

**Comment by RehabMan** [comment]
Report to kozlek.  Be sure to identify which part of that commit (changes to LPCSensors, or changes to HwMonitor for "some Seagate"?)

**Comment by RehabMan** [comment]
Issue is being tracked here: https://github.com/kozlek/HWSensors/issues/361
Closing issue here.
