### ISSUE TITLE
KP with Pascal GPU

### ISSUE THREAD

**Issue by icex** [RehabMan/OS-X-FakeSMC-kozlek#13]
I've just upgraded my GTX 660 to a 1070. But now I get a KP with FakeSMC_GPUSensors.kext. Everything works fine if I remove that kext.
![img_1935](https://cloud.githubusercontent.com/assets/2853554/25329728/b791ce3c-28e5-11e7-958b-edd6bf614872.JPG)

**Comment by RehabMan** [comment]
No idea on Pascal support.  You should refer to kozlek's branch and see if the same happens there.
My sources are up-to-date with kozlek's master.
