### ISSUE TITLE
How to install FakeSMC_*.kext?

### ISSUE THREAD

**Issue by Praying** [RehabMan/OS-X-FakeSMC-kozlek#14]
I tried put FakeSMC_*kext into /Library/Extensions/FakeSMC.kext/Context/PlugIns/,then reboot ,but it doesn't work. 

And my CPU is 7700K ,

Can you give me some guide? Thanks

**Comment by RehabMan** [comment]
There is no need to put the plugins in a PlugIns directory.
Install the kexts directly as  you would any kext.

**Comment by Praying** [comment]
Thanks a lot.I put it into the EFI/Clover/kexts/others and restart , and it works
