### ISSUE TITLE
Broadwell - Unsupported CPU Error

### ISSUE THREAD

**Issue by cfis** [RehabMan/OS-X-FakeSMC-kozlek#4]
Using RehabMan-FakeSMC-2015-0504.zip, when I boot my laptop I get the kernel panic below. The laptop is a Thinkpad T450s running with an Intel Core i5 2.59 GHZ Broadwell chip with Intel 5500 integrated graphics.  This is using just FakeSMC.kext, no plugins are installed.

---------------------------------

Mon Sep  7 17:28:38 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff7f817d2358): "Unsupported CPU"@/Users/kozlek/Documents/HWSensors/Shared/cpuid.h:698
Backtrace (CPU 0), Frame : Return Address
0xffffff81709dbce0 : 0xffffff800032bda1 
0xffffff81709dbd60 : 0xffffff7f817d2358 
0xffffff81709dbe70 : 0xffffff80008b3cad 
0xffffff81709dbeb0 : 0xffffff80008b379f 
0xffffff81709dbf30 : 0xffffff80008ae553 
0xffffff81709dbf70 : 0xffffff80008b4443 
0xffffff81709dbfb0 : 0xffffff80004125b7 
      Kernel Extensions in backtrace:
         org.hwsensors.driver.CPUSensors(1328.0)[2227862F-9B94-341B-9274-15783442BEEE]@0xffffff7f817d0000->0xffffff7f817d7fff
            dependency: org.netkas.driver.FakeSMC(1328)[1368FF02-1329-346F-98D6-599CE439340E]@0xffffff7f81776000

BSD process name corresponding to current thread: kernel_task
Boot args: -v PCIRootUID=1 kext-dev-mode=1 rootless=0 dart=0 -gux_defer_usb2 cpus=2 nv_disable=1   "Kernel=/System/Library/Kernels/kernel" slide=0 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64
Kernel UUID: 4B3A11F4-77AA-3D27-A22D-81A1BC5B504D
__HIB  text base: 0xffffff8000100000
System model name: MacBookPro12,1 (Mac-E43C1C25D4880AD6)

System uptime in nanoseconds: 1015552759
last loaded kext at 988976051: com.apple.driver.AppleEFINVRAM	2.0 (addr 0xffffff7f81f2f000, size 45056)
loaded kexts:
org.hwsensors.driver.ACPISensors	1328
org.hwsensors.driver.CPUSensors	1328
org.netkas.driver.FakeSMC	1328
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	396
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

**Comment by RehabMan** [comment]
Known problem with CPUSensors.kext.  Maybe when I get Broadwell hardware, I'll look into it.

But I don't even use the PlugIns anymore. They are not CPU efficient, not battery efficient.  And you really don't need them (there are other tools to monitor power usage from Intel).

**Comment by cfis** [comment]
Just to be clear, I don't think I have any of the plugins installed.   Just FakeSMC.kext and there is no plugins folder inside of it since I deleted it.  It is installed in /System/Library/Extensions.  Nor do I have any extensions installed on the EFI partition under /Volumes/efi/EFI/CLOVER/kexts/Other (I deleted all the specific OS X version folders).

Also that kext does not seem loaded:
kextstat | grep -i CPUSensors

So...a bit lost where this could be coming from.  Does clover have built-in version of FakeSMC?  Or is this in FakeSMC itself?

**Comment by RehabMan** [comment]
Your panic report clearly shows you have the plugins installed and loading...

org.hwsensors.driver.ACPISensors 1328
org.hwsensors.driver.CPUSensors 1328

They can exist as separate kexts installed to /S/L/E root, or inside FakeSMC.kext as plugins at FakeSMC.kext/Contents/PlugIns.

You may also be injecting FakeSMC and the plugins via EFI/Clover/kexts.

**Comment by cfis** [comment]
I finally figured out what caused this.  The plugins were not installed (which I knew and why this was baffling).  Instead, there was a exception report stored in nvram that OSX always picked up.  I think that happened because I decided to stop using EmuVariableUEFI.efi (which did work fine).

**Comment by RehabMan** [comment]
Still an issue with Broadwell and CPUSensors.kext, which I'll look into when I get Broadwell hardware.

Re-opening it to remind me.

**Comment by Geoferry** [comment]
Hi, can CPUSensors.kext work well with Broadwell now?

**Comment by RehabMan** [comment]
Probably now with latest build.  I have not tested it, as I have no Broadwell hardware.

**Comment by Geoferry** [comment]
Well, the HWMonitor can successfully load my CPU's(ThinkPad W550s) state. Is there anything else I should test?

**Comment by RehabMan** [comment]
Assuming your W550s has a Broadwell CPU, and FakeSMC_CPUSensors.kext is not crashing, and HwMonitor shows the frequencies/pstates/temperatures, then it sounds like it is fixed...

**Comment by Geoferry** [comment]
Yes, it's I7 5600U. And HwMonitor shows only frequencies &  temperatures, I cannot find any info about pstates. Is it called "CPU package Multiplier" ?

**Comment by Geoferry** [comment]
And another question is:

Cause my CPU is 2/4, HwMonitor/istatmenus could only show the information about the cores of CPU, how to manage it to show the information of threads?

**Comment by RehabMan** [comment]
> Is it called "CPU package Multiplier" ?
Yes
> how to manage it to show the information of threads?
Only info about each core is available from the MSRs.

**Comment by ysh09234** [comment]
( desktop CPU broadwell - i5 5675c ) not working..

fakesmc plugins > kernel panic

**Comment by RehabMan** [comment]
> ( desktop broadwell - i5 5675c ) not working..

You will need to provide specifics if you expect any kind of response.

**Comment by tt00023** [comment]
ysh09234 / 
5600U - Mobile
5675C - Desktop

vary

**Comment by ysh09234** [comment]
https://drive.google.com/file/d/0B4-ytbJH5oQCZ19Vbks2alQwdGc/view?usp=sharing

broadwell 5675c , 5775c  install fail..

fakesmc plugins 15-05-04 -> automatically reboot
fakesmc plugins 15-12-30 -> automatically reboot

**Comment by RehabMan** [comment]
Remove CPUSensors plugin.

**Comment by alexprowars** [comment]
cpu spec

machdep.cpu.brand_string: Intel(R) Core(TM) i5-5675C CPU @ 3.10GHz
machdep.cpu.family: 6
machdep.cpu.model: 71

**Comment by IchigoWalker** [comment]
The same error here. CPU Model: i7 5700HQ (Broadwell)

**Comment by rhcp011235** [comment]
Not sure if this has been fixed yet? I saw you merge stuff in from a few days ago.

Intel Core i7-6950X 3.0GHz (Broadwell) 

Not sure what other info you may need. But open to help in anyway possible

**Comment by RehabMan** [comment]
I merged some changes from the kozlek repo...
For you to test, since I have no Broadwell+ desktop hardware.
