### ISSUE TITLE
Download failing

### ISSUE THREAD

**Issue by Richie765** [RehabMan/OS-X-FakeSMC-kozlek#5]
Hi RehabMan!

I tried to download the latest build from the link below, but it consistently gives me a 0 length file. I tried on different computers. Could you take a look at it? Thanks!

Richard

https://bitbucket.org/RehabMan/os-x-fakesmc-kozlek/downloads/RehabMan-FakeSMC-2015-1230.zip

**Comment by RehabMan** [comment]
It was some sort of bitbucket snafu.  It was fine for a while, then suddenly not working.  Some sort of problem on the bitbucket server must have corrupted the file.  I removed it, and re-uploaded, now all is fine.
