### ISSUE TITLE
Is it possible to use FakeSMC to get rid of "overconsumption limitation" on a real Mac?

### ISSUE THREAD

**Issue by oscarstv** [RehabMan/OS-X-FakeSMC-kozlek#7]
Can fakeSMC bypass the Apple "overconsumption protection"?

I have the MBP2,2 battery dead. If I use Geekbench 3 with it, I get a benchmark of about 537 (single processor, 32-bit). If I use the good battery from my MBP3,1 into my MBP2,2 I get a benchmark of about 1008.

It's supposed this is done by Apple to protect the computer to shutdown while working, because the Magsafe has less power than the power the Mac could need in some situations. So, **Apple downclocks the CPU to the half of its real/nominal speed when battery is dead.**
The reality, I have a 85W Magsafe and if I reproduce a 1080 HD video (on my El Capitan MBP3,1) I get a real power drain of only about 49 W with full brightness, WIFI...
So, I think Apple does this to have us thinking we need a new Mac because ours is old and slow, not because of a supposed overconsumption situation.

This affects to Yosemite, El Capitan, (I think) older versions of OS X... and even BootCamp Windows 10. **So, I suppose this is done by SMC and not by OS X.**

**Is there something that can be done with FakeSMC to solve this?**

Thank you very much,

**Comment by RehabMan** [comment]
The status may be based on battery status, which is provided by AppleSmartBatteryManager.kext, not the SMC.

It is probably easiest to just fix your battery.
