### ISSUE TITLE
Sensor Notebook

### ISSUE THREAD

**Issue by ettoreribaudo** [RehabMan/OS-X-FakeSMC-kozlek#8]
Good morning, please i can create a patch for sensor of Asus UX501VW?
Regards
Ettore

**Comment by RehabMan** [comment]
You can get CPU temps/frequencies with FakeSMC_CPUSensors.kext.
If you're trying to get fan speeds or other temperature data, you need to reverse engineer your DSDT, and provide the necessary code (in an SSDT or patched DSDT) for ACPISensors.kext.
